# Generated by Django 5.1.1 on 2025-10-02 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyliaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('shopify_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('shopify_handle', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_stock', models.IntegerField(default=0)),
                ('variant_count', models.IntegerField(default=0)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('is_active_in_stylia', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('updated', 'Updated'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('data_hash', models.CharField(max_length=64)),
                ('shopify_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('products_created', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('products_deleted', models.IntegerField(default=0)),
                ('products_errors', models.IntegerField(default=0)),
                ('stylia_products_count', models.IntegerField(default=0)),
            ],
        ),
    ]
