# Generated by Django 5.1.1 on 2025-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncapp', '0003_push_error_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(help_text='Shopify shop domain, e.g. example-store.myshopify.com', max_length=255, unique=True)),
                ('access_token', models.CharField(help_text='Admin API access token', max_length=255)),
                ('scopes', models.CharField(blank=True, max_length=512)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
