# Generated by Django 5.2.6 on 2025-10-22 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncapp', '0004_shopifyapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('shopify_variant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory_item_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shopify_product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stylia_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='syncapp.styliaproduct')),
            ],
            options={
                'unique_together': {('stylia_product', 'sku')},
            },
        ),
    ]
