# Generated by Django 5.2.6 on 2025-10-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syncapp", "0005_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="synclog",
            name="products_existing",
            field=models.IntegerField(default=0),
        ),
    ]
