# Generated by Django 5.2.6 on 2025-10-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncapp', '0006_synclog_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styliaproduct',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('updated', 'Updated'), ('failed', 'Failed'), ('deleted', 'Deleted'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
